name: schoolworkspro_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


#change env
# Check this in newVersion package 'key: \'ds:5\''
version: 3.2.6+127
#  42 (1.0.41)

#version: 1.1.64+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.7
  fluttertoast: ^8.0.8
  fluttericon: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  get: ^4.3.8
  youtube_player_flutter: ^8.0.0
  open_url: ^2.0.0
  percent_indicator: ^4.2.2
  url_launcher: ^6.0.12
  readmore: ^2.1.0
  rich_readmore: ^1.0.3
  provider: ^6.0.1
  image_picker: ^1.0.1
  overlay_kit: ^1.0.8
  upgrader: ^4.2.0
  #  animated_splash_screen: ^1.1.0
  fl_chart: ^0.61.0
  flutter_rating_bar: ^4.0.0
  flutter_html: ^2.2.1
  rflutter_alert: ^2.0.4
  flutter_speed_dial: ^6.0.0
  multi_select_flutter: ^4.1.3
  grouped_list: ^5.0.1
  group_list_view:
  collection: ^1.17.0
  flutter_easyloading: ^3.0.3
  simple_html_css: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.6
  flutter_pdfview: ^1.2.1
  group_radio_button: ^1.1.0
  group_button: ^5.0.1
  webview_flutter:
  new_version: any
  form_field_validator: ^1.1.0
  getwidget: ^3.0.1
  dotted_border: ^2.0.0
  advance_pdf_viewer: ^2.0.1
  toggle_switch: ^2.0.1
  loader_overlay: ^2.0.5+1
  lottie: ^2.3.2
  sliding_up_panel: ^2.0.0+1
  modal_bottom_sheet: ^3.0.0-pre
  html_editor_enhanced: ^2.5.1
  firebase_messaging: ^13.0.1
  flutter_local_notifications: ^9.4.0
  firebase_core: ^1.14.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  dropdown_search: ^2.0.1
  #  flutter_zoom_drawer: ^3.0.2
  local_auth: ^2.1.0
  shimmer: ^2.0.0
  flutter_tts: ^3.6.3
  syncfusion_flutter_calendar: ^20.1.56
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56
  page_transition: ^2.0.5
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.0
  flutter_dotenv: ^5.0.2
  in_app_update: ^4.0.1
  #  system_alert_window: ^1.1.2
  share_plus: ^6.3.2
  date_time_picker: ^2.1.0
  dio: ^5.1.1
  buttons_tabbar: ^1.3.6
  crypto: ^3.0.2
  encrypt: ^5.0.1
  socket_io_client: ^2.0.1
  flutter_sticky_header: ^0.6.5
  sticky_headers: ^0.3.0+2
  bubble: ^1.2.1
  animated_text_kit: ^4.2.2
  flutter_chat_ui: ^1.6.4
  flutter_linkify: ^5.0.2
  flutter_markdown: ^0.6.19
  multi_dropdown:


dependency_overrides:
  flutter_svg: ^1.0.3
  firebase_core_platform_interface: 4.5.1
  syncfusion_flutter_pdfviewer:
  photo_view: ^0.14.0
  pdf:
  syncfusion_flutter_pdf:
  syncfusion_flutter_datepicker:
  cached_network_image: ^3.2.3
  package_info_plus: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/StudentDashboard/
    - assets/images/home/
    - assets/images/button/
    - assets/icons/
    - assets/icons/profileicons/
    - assets/icons/Lecturerprofileicons/
    - assets/icons/svg/
    - assets/
    - assets/partners/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages